import {
  ReactNode,
  SetStateAction,
  createContext,
  useEffect,
  useContext as useReactContext,
  useState,
} from "react";

export enum AssistanceType {
  FIXED = "FIXED",
  MOBILE = "MOBILE",
}

const defaultContext = {
  context: {
    logged: false,
    shopId: null,
    assistance: [
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 1 - Mendoza",
        address: "9 de Julio 500, Mendoza, Argentina",
        location: { lat: -32.89765923961716, lng: -68.84286361623253 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 2 - Mendoza",
        address: "San Martín 300, Mendoza, Argentina",
        location: { lat: -32.890243, lng: -68.855215 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 3 - Mendoza",
        address: "Belgrano 700, Mendoza, Argentina",
        location: { lat: -32.893877, lng: -68.833646 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 4 - Mendoza",
        address: "Las Heras 450, Mendoza, Argentina",
        location: { lat: -32.892671, lng: -68.839463 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 5 - Mendoza",
        address: "Gral. Paz 550, Mendoza, Argentina",
        location: { lat: -32.892308, lng: -68.857268 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 7 - Mendoza",
        address: "San Juan 350, Mendoza, Argentina",
        location: { lat: -32.89259, lng: -68.868067 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.FIXED,
        contact: "Tel. +54 9 11 5555-5555",
        name: "Centro de asistencia 8 - Mendoza",
        address: "Patricias Mendocinas 600, Mendoza, Argentina",
        location: { lat: -32.889083, lng: -68.863861 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.MOBILE,
        location: { lat: -32.904925, lng: -68.872707 },
        schedule: "De 08:00hs a 18:00hs",
      },
      {
        type: AssistanceType.MOBILE,
        location: { lat: -32.891728, lng: -68.855743 },
        schedule: "De 08:00hs a 18:00hs",
      },
    ],
    attractions: [
      {
        id: 1,
        name: "Parque General San Martín",
        descrition: "",
        image: "/parque-general-san-martin.jpg",
      },
      {
        id: 2,
        name: "Plaza Independencia",
        descrition: "",
        image: "/plaza-independencia.jpg",
      },
      {
        id: 3,
        name: "Fuente de los continentes",
        descrition: "",
        image: "/fuente-de-los-continentes.jpg",
      },
      {
        id: 4,
        name: "Museo de Ciencias Naturales y Antropológicas",
        descrition: "",
        image: "/museo-de-ciencias-naturales-y-antropologicas.jpg",
      },
      {
        id: 5,
        name: "Monumento al Ejército de Los Andes",
        descrition: "",
        image: "/monumento-al-ejercito-de-los-andes.jpeg",
      },
      {
        id: 6,
        name: "Museo del Área Fundacional",
        descrition: "",
        image: "/museo-del-area-fundacional.jpg",
      },
    ],
    shops: [
      {
        id: 1,
        name: "La Bodega del Sol",
        description: "Tienda de productos regionales mendocinos",
        address: "Av. San Martín 123, Mendoza, Argentina",
        schedule: "De 10hs a 20hs",
        contact: "Tel. +54 9 261 555-1234",
        image: "/comercio.jpg",
        location: { lat: -32.896512, lng: -68.845721 },
      },
      {
        id: 2,
        name: "Sabores de la Tierra",
        description: "Especialidades locales y vinos de la región",
        address: "Calle Belgrano 456, Mendoza, Argentina",
        schedule: "De 10hs a 19hs",
        contact: "Tel. +54 9 261 555-5678",
        image: "/comercio.jpg",
        location: { lat: -32.894231, lng: -68.838927 },
      },
      {
        id: 3,
        name: "El Rincón de los Andes",
        description: "Productos artesanales de la cordillera",
        address: "Av. Las Heras 789, Mendoza, Argentina",
        schedule: "De 9hs a 18hs",
        contact: "Tel. +54 9 261 555-9876",
        image: "/comercio.jpg",
        location: { lat: -32.891876, lng: -68.839642 },
      },
      {
        id: 4,
        name: "Gastronomía Cuyana",
        description: "Sabores típicos de la región cuyana",
        address: "Espejo 345, Mendoza, Argentina",
        schedule: "De 11hs a 21hs",
        contact: "Tel. +54 9 261 555-6543",
        image: "/comercio.jpg",
        location: { lat: -32.897543, lng: -68.846219 },
      },
      {
        id: 5,
        name: "Mendoza Gourmet",
        description: "Delicias gourmet y vinos de autor",
        address: "Av. Sarmiento 678, Mendoza, Argentina",
        schedule: "De 12hs a 22hs",
        contact: "Tel. +54 9 261 555-2345",
        image: "/comercio.jpg",
        location: { lat: -32.895412, lng: -68.850112 },
      },
      {
        id: 6,
        name: "Artesanías Cuyanas",
        description: "Artesanías y productos regionales",
        address: "San Juan 567, Mendoza, Argentina",
        schedule: "De 10hs a 19hs",
        contact: "Tel. +54 9 261 555-8765",
        image: "/comercio.jpg",
        location: { lat: -32.893765, lng: -68.839018 },
      },
      {
        id: 7,
        name: "Tierra de Sabores",
        description: "Productos naturales y orgánicos",
        address: "Av. Mitre 432, Mendoza, Argentina",
        schedule: "De 9hs a 17hs",
        contact: "Tel. +54 9 261 555-5432",
        image: "/comercio.jpg",
        location: { lat: -32.892134, lng: -68.841927 },
      },
      {
        id: 8,
        name: "Ruta de los Vinos",
        description: "Vinos y productos de bodegas locales",
        address: "Urquiza 789, Mendoza, Argentina",
        schedule: "De 11hs a 20hs",
        contact: "Tel. +54 9 261 555-7890",
        image: "/comercio.jpg",
        location: { lat: -32.889765, lng: -68.847312 },
      },
      {
        id: 9,
        name: "Sabor Andino",
        description: "Especialidades de la gastronomía andina",
        address: "Av. General Paz 567, Mendoza, Argentina",
        schedule: "De 10hs a 18hs",
        contact: "Tel. +54 9 261 555-4321",
        image: "/comercio.jpg",
        location: { lat: -32.894567, lng: -68.849543 },
      },
      {
        id: 10,
        name: "Aromas del Valle",
        description: "Aromas y sabores del valle de Uco",
        address: "25 de Mayo 876, Mendoza, Argentina",
        schedule: "De 12hs a 21hs",
        contact: "Tel. +54 9 261 555-2109",
        image: "/comercio.jpg",
        location: { lat: -32.891234, lng: -68.854219 },
      },
      {
        id: 11,
        name: "El Patio de las Delicias",
        description: "Productos regionales en un ambiente encantador",
        address: "San Martín 789, Mendoza, Argentina",
        schedule: "De 10hs a 19hs",
        contact: "Tel. +54 9 261 555-8765",
        image: "/comercio.jpg",
        location: { lat: -32.895678, lng: -68.846543 },
      },
      {
        id: 12,
        name: "Mendoza Natural",
        description: "Productos naturales y orgánicos de la región",
        address: "Av. Las Heras 567, Mendoza, Argentina",
        schedule: "De 9hs a 18hs",
        contact: "Tel. +54 9 261 555-4321",
        image: "/comercio.jpg",
        location: { lat: -32.892456, lng: -68.843721 },
      },
      {
        id: 13,
        name: "Rincón Cuyano",
        description: "Especialidades culinarias de Cuyo",
        address: "Sarmiento 432, Mendoza, Argentina",
        schedule: "De 11hs a 20hs",
        contact: "Tel. +54 9 261 555-7890",
        image: "/comercio.jpg",
        location: { lat: -32.896543, lng: -68.839876 },
      },
      {
        id: 14,
        name: "Vinos y Sabores",
        description: "Selección de vinos y productos gourmet",
        address: "Belgrano 678, Mendoza, Argentina",
        schedule: "De 10hs a 18hs",
        contact: "Tel. +54 9 261 555-2109",
        image: "/comercio.jpg",
        location: { lat: -32.893765, lng: -68.845219 },
      },
      {
        id: 15,
        name: "Mendoza Tradicional",
        description: "Productos tradicionales de la región",
        address: "San Juan 789, Mendoza, Argentina",
        schedule: "De 12hs a 21hs",
        contact: "Tel. +54 9 261 555-5432",
        image: "/comercio.jpg",
        location: { lat: -32.891234, lng: -68.848312 },
      },
      {
        id: 16,
        name: "Gourmet Andino",
        description: "Gastronomía gourmet con toques andinos",
        address: "Urquiza 567, Mendoza, Argentina",
        schedule: "De 9hs a 17hs",
        contact: "Tel. +54 9 261 555-8765",
        image: "/comercio.jpg",
        location: { lat: -32.894567, lng: -68.846543 },
      },
      {
        id: 17,
        name: "Sabor a Uco",
        description: "Sabores auténticos del valle de Uco",
        address: "General Paz 567, Mendoza, Argentina",
        schedule: "De 10hs a 19hs",
        contact: "Tel. +54 9 261 555-4321",
        image: "/comercio.jpg",
        location: { lat: -32.895678, lng: -68.842721 },
      },
      {
        id: 18,
        name: "El Mercado del Valle",
        description: "Productos frescos del valle",
        address: "25 de Mayo 432, Mendoza, Argentina",
        schedule: "De 11hs a 20hs",
        contact: "Tel. +54 9 261 555-7890",
        image: "/comercio.jpg",
        location: { lat: -32.896543, lng: -68.839876 },
      },
      {
        id: 19,
        name: "Raíces Mendocinas",
        description: "Productos con auténtico sabor mendocino",
        address: "Las Heras 678, Mendoza, Argentina",
        schedule: "De 10hs a 18hs",
        contact: "Tel. +54 9 261 555-2109",
        image: "/comercio.jpg",
        location: { lat: -32.894567, lng: -68.841543 },
      },
      {
        id: 20,
        name: "Aromas del Cuyo",
        description: "Aromas y sabores característicos de Cuyo",
        address: "Sarmiento 789, Mendoza, Argentina",
        schedule: "De 12hs a 21hs",
        contact: "Tel. +54 9 261 555-5432",
        image: "/comercio.jpg",
        location: { lat: -32.891234, lng: -68.848312 },
      },
    ],
    products: [
      {
        id: 1,
        name: "Aceite de Oliva Extra Virgen",
        description: "Elaborado con aceitunas de la región",
        price: 4500,
        image: "/product-default.png",
        characteristics: "Frasco de 500ml",
        shopId: 1,
        type: "item",
        categoryId: 1,
      },
      {
        id: 2,
        name: "Vino Malbec Reserva",
        description: "Vino tinto de alta calidad",
        price: 12000,
        image: "/product-default.png",
        characteristics: "Botella de 750ml",
        shopId: 2,
        type: "item",
        categoryId: 2,
      },
      {
        id: 3,
        name: "Dulce de Membrillo Artesanal",
        description: "Elaborado con membrillos de la región",
        price: 3000,
        image: "/product-default.png",
        characteristics: "Envase de 400g",
        shopId: 3,
        type: "item",
        categoryId: 1,
      },
      {
        id: 4,
        name: "Choclo en Conserva",
        description: "Maíz tierno en conserva",
        price: 1500,
        image: "/product-default.png",
        characteristics: "Lata de 300g",
        shopId: 4,
        type: "item",
        categoryId: 1,
      },
      {
        id: 5,
        name: "Mermelada de Frutos del Bosque",
        description: "Elaborada con frutos frescos de la región",
        price: 4000,
        image: "/product-default.png",
        characteristics: "Frasco de 250g",
        shopId: 5,
        type: "item",
        categoryId: 1,
      },
      {
        id: 6,
        name: "Queso de Cabra Artesanal",
        description: "Queso elaborado con leche de cabra",
        price: 8000,
        image: "/product-default.png",
        characteristics: "Pieza de 300g",
        shopId: 6,
        type: "item",
        categoryId: 1,
      },
      {
        id: 7,
        name: "Tomates Secos",
        description: "Tomates deshidratados al sol",
        price: 6000,
        image: "/product-default.png",
        characteristics: "Envase de 150g",
        shopId: 7,
        type: "item",
        categoryId: 1,
      },
      {
        id: 8,
        name: "Aceitunas Marinadas",
        description: "Aceitunas con hierbas y especias",
        price: 3500,
        image: "/product-default.png",
        characteristics: "Frascos de 200g",
        shopId: 8,
        type: "item",
        categoryId: 1,
      },
      {
        id: 9,
        name: "Harina de Almendra",
        description: "Harina fina de almendra",
        price: 12000,
        image: "/product-default.png",
        characteristics: "Bolsa de 500g",
        shopId: 9,
        type: "item",
        categoryId: 1,
      },
      {
        id: 10,
        name: "Honey Stout Artesanal",
        description: "Cerveza artesanal con miel",
        price: 5000,
        image: "/product-default.png",
        characteristics: "Botella de 330ml",
        shopId: 10,
        type: "item",
        categoryId: 2,
      },
      {
        id: 11,
        name: "Mermelada de Durazno",
        description: "Elaborada con duraznos de la región",
        price: 3500,
        image: "/product-default.png",
        characteristics: "Frasco de 250g",
        shopId: 11,
        type: "item",
        categoryId: 1,
      },
      {
        id: 12,
        name: "Sal de la Cordillera",
        description: "Sal marina recolectada en la cordillera",
        price: 2000,
        image: "/product-default.png",
        characteristics: "Envase de 500g",
        shopId: 12,
        type: "item",
        categoryId: 1,
      },
      {
        id: 13,
        name: "Miel de Abejas Silvestres",
        description: "Miel pura de abejas silvestres",
        price: 6000,
        image: "/product-default.png",
        characteristics: "Frascos de 300g",
        shopId: 13,
        type: "item",
        categoryId: 1,
      },
      {
        id: 14,
        name: "Salsa Chimichurri",
        description: "Salsa tradicional para carnes",
        price: 2500,
        image: "/product-default.png",
        characteristics: "Frascos de 200ml",
        shopId: 14,
        type: "item",
        categoryId: 1,
      },
      {
        id: 15,
        name: "Alfajores de Maicena",
        description: "Dulce tradicional de la región",
        price: 1800,
        image: "/product-default.png",
        characteristics: "Paquete de 6 unidades",
        shopId: 15,
        type: "item",
        categoryId: 1,
      },
      {
        id: 16,
        name: "Aceitunas Rellenas",
        description: "Aceitunas rellenas de pimientos",
        price: 4000,
        image: "/product-default.png",
        characteristics: "Frascos de 250g",
        shopId: 16,
        type: "item",
        categoryId: 1,
      },
      {
        id: 17,
        name: "Vino Torrontés",
        description: "Vino blanco aromático",
        price: 10000,
        image: "/product-default.png",
        characteristics: "Botella de 750ml",
        shopId: 17,
        type: "item",
        categoryId: 2,
      },
      {
        id: 18,
        name: "Dulce de Higo",
        description: "Elaborado con higos frescos",
        price: 3000,
        image: "/product-default.png",
        characteristics: "Frasco de 200g",
        shopId: 18,
        type: "item",
        categoryId: 1,
      },
      {
        id: 19,
        name: "Queso Azul",
        description: "Queso azul de producción artesanal",
        price: 9000,
        image: "/product-default.png",
        characteristics: "Pieza de 250g",
        shopId: 19,
        type: "item",
        categoryId: 1,
      },
      {
        id: 20,
        name: "Cerveza IPA Artesanal",
        description: "Cerveza India Pale Ale",
        price: 5500,
        image: "/product-default.png",
        characteristics: "Botella de 330ml",
        shopId: 20,
        type: "item",
        categoryId: 2,
      },
      {
        id: 21,
        name: "Aceitunas Verdes en Salmuera",
        description: "Aceitunas verdes conservadas en salmuera",
        price: 3000,
        image: "/product-default.png",
        characteristics: "Frascos de 200g",
        shopId: 1,
        type: "item",
        categoryId: 1,
      },
      {
        id: 22,
        name: "Vino Cabernet Sauvignon",
        description: "Vino tinto con sabor intenso",
        price: 11000,
        image: "/product-default.png",
        characteristics: "Botella de 750ml",
        shopId: 2,
        type: "item",
        categoryId: 2,
      },
      {
        id: 23,
        name: "Dulce de Cayote",
        description: "Elaborado con cayotes de la región",
        price: 3200,
        image: "/product-default.png",
        characteristics: "Frasco de 300g",
        shopId: 3,
        type: "item",
        categoryId: 1,
      },
      {
        id: 24,
        name: "Maíz Morado",
        description: "Maíz morado para preparaciones especiales",
        price: 1800,
        image: "/product-default.png",
        characteristics: "Paquete de 500g",
        shopId: 4,
        type: "item",
        categoryId: 1,
      },
      {
        id: 25,
        name: "Compota de Manzana",
        description: "Compota casera de manzana",
        price: 2500,
        image: "/product-default.png",
        characteristics: "Frasco de 400g",
        shopId: 5,
        type: "item",
        categoryId: 1,
      },
      {
        id: 26,
        name: "Queso Provolone",
        description: "Queso provolone ahumado",
        price: 7500,
        image: "/product-default.png",
        characteristics: "Pieza de 400g",
        shopId: 6,
        type: "item",
        categoryId: 1,
      },
      {
        id: 27,
        name: "Ciruelas Deshidratadas",
        description: "Ciruelas deshidratadas sin azúcar añadida",
        price: 4000,
        image: "/product-default.png",
        characteristics: "Envase de 250g",
        shopId: 7,
        type: "item",
        categoryId: 1,
      },
      {
        id: 28,
        name: "Aceite de Almendra",
        description: "Aceite de almendra prensado en frío",
        price: 8000,
        image: "/product-default.png",
        characteristics: "Botella de 250ml",
        shopId: 8,
        type: "item",
        categoryId: 1,
      },
      {
        id: 29,
        name: "Masa para Tartas",
        description: "Masa artesanal para tartas",
        price: 3500,
        image: "/product-default.png",
        characteristics: "Paquete de 500g",
        shopId: 9,
        type: "item",
        categoryId: 1,
      },
      {
        id: 30,
        name: "Cerveza Stout Ahumada",
        description: "Cerveza stout con notas ahumadas",
        price: 6000,
        image: "/product-default.png",
        characteristics: "Botella de 330ml",
        shopId: 10,
        type: "item",
        categoryId: 2,
      },
      {
        id: 31,
        name: "Miel de Monte",
        description: "Miel recolectada en las montañas",
        price: 5000,
        image: "/product-default.png",
        characteristics: "Frascos de 300g",
        shopId: 11,
        type: "item",
        categoryId: 1,
      },
      {
        id: 32,
        name: "Salsa Barbacoa",
        description: "Salsa para barbacoa con especias regionales",
        price: 2800,
        image: "/product-default.png",
        characteristics: "Frascos de 200ml",
        shopId: 12,
        type: "item",
        categoryId: 1,
      },
      {
        id: 33,
        name: "Almendras Tostadas",
        description: "Almendras tostadas y saladas",
        price: 3200,
        image: "/product-default.png",
        characteristics: "Envase de 150g",
        shopId: 13,
        type: "item",
        categoryId: 1,
      },
      {
        id: 34,
        name: "Vino Torrontel",
        description: "Vino blanco fresco y afrutado",
        price: 9500,
        image: "/product-default.png",
        characteristics: "Botella de 750ml",
        shopId: 14,
        type: "item",
        categoryId: 2,
      },
      {
        id: 35,
        name: "Dulce de Leche Artesanal",
        description: "Dulce de leche casero",
        price: 3800,
        image: "/product-default.png",
        characteristics: "Frasco de 400g",
        shopId: 15,
        type: "item",
        categoryId: 1,
      },
      {
        id: 36,
        name: "Queso Gouda",
        description: "Queso gouda madurado",
        price: 8500,
        image: "/product-default.png",
        characteristics: "Pieza de 350g",
        shopId: 16,
        type: "item",
        categoryId: 1,
      },
      {
        id: 37,
        name: "Higos en Almíbar",
        description: "Higos en almíbar artesanal",
        price: 4200,
        image: "/product-default.png",
        characteristics: "Frascos de 250g",
        shopId: 17,
        type: "item",
        categoryId: 1,
      },
      {
        id: 38,
        name: "Aceitunas Negras en Salmuera",
        description: "Aceitunas negras conservadas en salmuera",
        price: 3300,
        image: "/product-default.png",
        characteristics: "Frascos de 200g",
        shopId: 18,
        type: "item",
        categoryId: 1,
      },
    ],
    categories: [
      {
        id: 1,
        name: "Alimentos",
      },
      {
        id: 2,
        name: "Bebidas",
      },
      {
        id: 3,
        name: "Ropa",
      },
      {
        id: 4,
        name: "Accesorios",
      },
      {
        id: 5,
        name: "Otros",
      },
    ],
  },
  setContext: (_value) => {},
};

const Context = createContext(defaultContext);

export const ContextProvider = ({ children }: { children: ReactNode }) => {
  const [context, setContextRaw] = useState(defaultContext.context);
  const setContext = (value: SetStateAction<{ user: null }>) => {
    const newContext = { ...context, ...value };
    setContextRaw(newContext);
    localStorage.setItem("context", JSON.stringify(newContext));
  };

  useEffect(() => {
    const localStorageContext = localStorage.getItem("context");
    if (localStorageContext) setContextRaw(JSON.parse(localStorageContext));
  }, []);

  return (
    <Context.Provider value={{ context, setContext }}>
      {children}
    </Context.Provider>
  );
};

export const useContext = () => {
  return useReactContext(Context);
};
